/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Item = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'price' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'total' : IDL.Nat,
  'paymentMethod' : IDL.Text,
  'timestamp' : Time,
  'isConfirmed' : IDL.Bool,
  'items' : IDL.Vec(Item),
  'receipts' : IDL.Vec(ExternalBlob),
});
export const RequestSummary = IDL.Record({
  'deliveryAddress' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'selectedItemsIds' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrderConfirmation' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'orderId' : IDL.Nat, 'confirmationMessage' : IDL.Text })],
      ['query'],
    ),
  'getOrderHistorySummary' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrderStatus' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'placeOrder' : IDL.Func([RequestSummary], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Item = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'total' : IDL.Nat,
    'paymentMethod' : IDL.Text,
    'timestamp' : Time,
    'isConfirmed' : IDL.Bool,
    'items' : IDL.Vec(Item),
    'receipts' : IDL.Vec(ExternalBlob),
  });
  const RequestSummary = IDL.Record({
    'deliveryAddress' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'selectedItemsIds' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrderConfirmation' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'orderId' : IDL.Nat, 'confirmationMessage' : IDL.Text })],
        ['query'],
      ),
    'getOrderHistorySummary' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrderStatus' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'placeOrder' : IDL.Func([RequestSummary], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };